<?php
/**
 * Bancha Project : Combining Ext JS and CakePHP (http://banchaproject.org)
 * Copyright 2011, Roland Schuetz, Kung Wong, Andreas Kern, Florian Eckerstorfer
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @package       Bancha
 * @category      tests
 * @copyright     Copyright 2011 Roland Schuetz, Kung Wong, Andreas Kern, Florian Eckerstorfer
 * @link          http://banchaproject.org Bancha Project
 * @since         Bancha v1.0
 * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @author        Florian Eckerstorfer <f.eckerstorfer@gmail.com>
 */

App::uses('BanchaResponseTransformer', 'Bancha.Bancha/Network');

/**
 * BanchaResponseTransformerTest
 *
 * @package       Bancha
 * @category      tests
 */
class BanchaResponseTransformerTest extends CakeTestCase {

/**
 * Tests the transform() method for the 'index' action.
 *
 */
	public function testTransformIndexAction() {
		// Response generated by CakePHP
		$cakeResponse = array(
			array(
				'Article'	=> array(
					'id'	=> 304,
					'title'	=> 'foo',
				),
			),
			array(
				'Article'	=> array(
					'id'	=> 305,
					'title'	=> 'bar',
				),
			)
		);

		$request = new CakeRequest();
		$request->addParams(array(
			'controller'	=> 'Articles',
			'action'		=> 'index',
		));

		// Response expected by Ext JS (in JSON).
		$expectedResponse = array(
			array(
				'id'	=> 304,
				'title'	=> 'foo',
			),
			array(
				'id'	=> 305,
				'title'	=> 'bar',
			)
		);

		$this->assertEquals($expectedResponse, BanchaResponseTransformer::transform($cakeResponse, $request));
	}

/**
 * Tests the transform() method for the 'view' action.
 *
 */
	public function testTransformViewAction() {
		// Response generated by CakePHP.
		$cakeResponse = array(
			'Article'	=> array(
				'id'	=> 304,
				'title'	=> 'foo',
			),
		);

		$request = new CakeRequest();
		$request->addParams(array(
			'controller'	=> 'Articles',
			'action'			=> 'view'
		));

		// Response expected by Ext JS (in JSON).
		$expectedResponse = array(
			array(
				'id'	=> 304,
				'title'	=> 'foo',
			),
		);

		$this->assertEquals($expectedResponse, BanchaResponseTransformer::transform($cakeResponse, $request));
	}

/**
 * Tests the transform() method for the 'add' action.
 *
 */
	public function testTransformAddAction() {
		// Response generated by CakePHP.
		$cakeResponse = array(
			'Article'	=> array(
				'id'	=> 304,
				'title'	=> 'foo',
			),
		);

		$request = new CakeRequest();
		$request->addParams(array(
			'controller'	=> 'Articles',
			'action'		=> 'add'
		));

		// Response expected by Ext JS (in JSON).
		$expectedResponse = array(
			'id'	=> 304,
			'title'	=> 'foo',
		);

		$this->assertEquals($expectedResponse, BanchaResponseTransformer::transform($cakeResponse, $request));
	}

/**
 * Tests the transform() method for the 'edit' action.
 *
 */
	public function testTransformEditAction() {
		// Response generated by CakePHP.
		$cakeResponse = array(
			'Article'	=> array(
				'id'	=> 304,
				'title'	=> 'foo',
			),
		);

		$request = new CakeRequest();
		$request->addParams(array(
			'controller'	=> 'Articles',
			'action'		=> 'edit'
		));

		// Response expected by Ext JS (in JSON).
		$expectedResponse = array(
			'id'	=> 304,
			'title'	=> 'foo',
		);

		$this->assertEquals($expectedResponse, BanchaResponseTransformer::transform($cakeResponse, $request));
	}

/**
 * Tests the transform() method for the 'delete' action.
 *
 */
	public function testTransformDeleteAction() {
		// Response generated by CakePHP.
		$cakeResponse = array();

		$request = new CakeRequest();
		$request->addParams(array(
			'controller'	=> 'Articles',
			'action'		=> 'delete'
		));

		// Response expected by Ext JS (in JSON)
		$expectedResponse = array();

		$this->assertEquals($expectedResponse, BanchaResponseTransformer::transform($cakeResponse, $request));
	}

/**
 * Tests the transform() method for extUpload actions.
 *
 */
	public function testTransformExtUploadAction() {
		// Response generated by CakePHP.
		$cakeResponse = array(
			'Article'	=> array(
				'id'	=> 304,
				'title'	=> 'foo',
			),
		);

		$request = new CakeRequest();
		$request->addParams(array(
			'controller'	=> 'Articles',
			'action'		=> 'add',
			'extUpload'		=> true,
		));

		// Response expected by Ext JS.
		$expectedResponse = '<html><body><textarea>' . str_replace('"', '\"', json_encode(array(
			'id'	=> 304,
			'title'	=> 'foo',
		))) . '</textarea></body></html>';

		$this->assertEquals($expectedResponse, BanchaResponseTransformer::transform($cakeResponse, $request));
	}

}
